# ClariFi AI - Render Deployment Configuration
services:
  # Backend API Service
  - type: web
    name: clarifi-ai-api
    runtime: python
    region: oregon
    rootDir: api
    plan: free  # Change to 'starter' or higher for production
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.13.4"
      # Do NOT set PORT manually; Render injects PORT dynamically at runtime
      # - key: PORT
      #   generateValue: true
      - key: ENVIRONMENT
        value: "production"
      - key: USE_LITE_EMBEDDINGS
        value: "true"
      - key: API_HOST
        value: "0.0.0.0"
      # Add your secret environment variables in Render Dashboard:
      # - MONGODB_URL or MONGODB_URI
      # - JWT_SECRET
      # - OPENAI_API_KEY (if using OpenAI)
      # - GOOGLE_API_KEY (if using Google AI)
      # - Any other API keys needed
    healthCheckPath: /health
    
  # Frontend Static Site (Optional - if deploying on Render instead of Vercel)
  # Uncomment below if you want to deploy frontend on Render
  # - type: web
  #   name: clarifi-ai-frontend
  #   runtime: node
  #   region: oregon
  #   rootDir: frontend
  #   plan: free
  #   buildCommand: npm install && npm run build
  #   staticPublishPath: ./dist
  #   routes:
  #     - type: rewrite
  #       source: /*
  #       destination: /index.html